version: '3.4'
services:
  ekart:
    image: sajipoochira/ekart
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ekart:/app/static
volumes:
  ekart:
     
