apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-db
  
spec:
  selector:
    matchLabels:
      app: ekart-db
  replicas: 5
  template:
    metadata:
      labels:
        app: ekart-db
    spec:
      containers:
               
      - name: postgres
        image: postgres
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: ekartdb
        env:
        - name: POSTGRES_USER
          value: postgres    
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
      volumes:
        - name: ekartdb