
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ekart
spec:
  resources:
    requests:
      storage: 1G
    limits:
      storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce